// Generated by CoffeeScript 1.8.0
(function() {
  var app, body_parser, express, get_type, html_dir, widget;

  express = require('express');

  body_parser = require('body-parser');

  app = express();

  app.set('port', process.env.PORT || 5000);

  app.use(express["static"](__dirname + '/public'));

  app.use(body_parser.json());

  app.use(body_parser.urlencoded({
    extended: true
  }));

  get_type = function(url) {
    if (url.match("[^\s]+\.(jpg|png|gif|bmp)")) {
      return "image";
    } else if (url.match("[^\s]+\.youtube\.com/watch\\?v=\w*")) {
      console.log('qq');
      return "youtube";
    } else {
      return "link";
    }
  };

  widget = function(url) {
    var id;
    switch (get_type(url)) {
      case "link":
        return "<a href=\"" + url + "\" >" + url + "</a>";
      case "image":
        return "<img src=\"" + url + "\">";
      case "youtube":
        id = url.match("[^\s]+\.youtube\.com/watch\?v=(\w*)");
        return "<iframe id=\"ytplayer\" type=\"text/html\" width=\"640\" height=\"390\" src=\"http://www.youtube.com/embed/" + id + "?autoplay=1&origin=http://example.com\"frameborder=\"0\"/>";
    }
  };

  html_dir = './public/';

  app.get('/', function(req, res) {
    return res.sendFile(html_dir + 'index.html');
  });

  app.get('/note', function(req, res) {
    return res.send("<html>\n<body>\n<h1>editor</h1>\n<div class=\"body\">\n        <form method=\"POST\" action=\"/publish\">\n                <input type=\"text\" name=\"input\" \>\n                <input type=\"submit\" \>\n        </form>\n</div>\n</body>\n</html>");
  });

  app.get('/note/:id', function(req, res) {
    return res.send(new Buffer(decodeURIComponent(req.params.id), 'base64').toString('ascii'));
  });

  app.post('/publish', function(req, res) {
    return res.send(encodeURIComponent(new Buffer(widget(decodeURIComponent(req.body.input))).toString('base64')));
  });

  app.listen(app.get('port'), function() {
    return console.log("Node app is running at localhost:" + app.get('port'));
  });

}).call(this);
